server:
  port: 8080
spring:
  application:
    #应用的名称，可选
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/regist?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: muyuzong666
  mail:
    username: 2715309233@qq.com
    password: ixzhceokhcrzdgdg
    host: smtp.qq.com
    default-encoding: UTF-8
    properties:
      mail:
        stmp:
          ssl:
            enable: true
            required: true
  redis:
    port: 6379
    host: localhost
#    password: muyuzong666
    database: 0
  cache:
    redis:
      time-to-live: 1800000 #ms
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: D:\SWUST\研二\Java\8-项目\1 瑞吉外卖项目\资料\图片资源\
